export const API_CONFIG = {
  REQUEST_TIMEOUT: 30000, // 30 seconds
  MAX_RETRY_ATTEMPTS: 3,
  BASE_RETRY_DELAY: 1000, // 1 second
  MAX_SEARCH_PAGES: 5,
  DEFAULT_PAGE_SIZE: 25,
  DEFAULT_SEARCH_LIMIT: 20,
  MAX_SEARCH_LIMIT: 100,
} as const;