export const API_CONFIG = {
  REQUEST_TIMEOUT: 30000, // 30 seconds
  MAX_RETRY_ATTEMPTS: 3,
  BASE_RETRY_DELAY: 1000, // 1 second
  MAX_SEARCH_PAGES: 5,
  DEFAULT_PAGE_SIZE: 25,
  DEFAULT_SEARCH_LIMIT: 20,
  MAX_SEARCH_LIMIT: 250,
  MAX_TAG_SEARCH_PAGES: 5,
  SEARCH_RESULTS_TTL: 600000, // 10 minutes
} as const;